[default]
JWT_SECRET = ""
ALGORITHM = ""

[production]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@10.0.0.4:5432/db_exemple_production"

[development]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@10.0.0.4:5432/db_exemple_development"

[testing]
JWT_SECRET = ""
DB_URI = "postgresql+asyncpg://postgres:Vish_123123@10.0.0.4:5432/db_exemple_testing"